spring.datasource.url=jdbc:mysql://localhost:3306/api_helpdesk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MS_USER}
spring.datasource.password=${MS_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
//spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.web.error.include-stacktrace=never